version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28-ndk-r17b
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Set Environmental Variables
        command: |
          git submodule init && git submodule update
          sdkmanager "cmake;3.6.3155560"
          sdkmanager --update
          echo y | sdkmanager --licenses
          echo "sdk.dir="$ANDROID_HOME > local.properties
          echo "ndk.dir="$ANDROID_NDK_HOME >> local.properties
          echo "" >> gradle.properties
          echo "ANDLOILO_KEY_PASSWORD="$ANDLOILO_KEY_PASSWORD >> gradle.properties
          echo "ANDLOILO_KEYSTORE_PASSWORD="$ANDLOILO_KEYSTORE_PASSWORD >> gradle.properties
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - run:
        name: TEST
        command: ls -l /opt/android/sdk/licenses
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Tests
        command: ./gradlew clean assembleRelease
    - run:
        name: Run Build For AndroidTest
        command: ./gradlew assembleAndroidTest
    - store_artifacts:
        path: app/build/outputs/apk/release
        destination: apk
    - store_artifacts:
        path: app/build/outputs/apk/androidTest/debug
        destination: apk
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
