version: 2.1

executors:
  default:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-ndk-r17b

commands:
  restore_gradle:
    steps:    
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  set_properties:
    steps:
      - run:
        name: set properties
        command: |
          git submodule init && git submodule update
          yes | sdkmanager --update || true
          yes | sdkmanager --licenses || true
          ls -l /opt/android/sdk/licenses
          echo "sdk.dir="$ANDROID_HOME > local.properties
          echo "ndk.dir="$ANDROID_NDK_HOME >> local.properties
          echo "" >> gradle.properties
          echo "ANDLOILO_KEY_PASSWORD="$ANDLOILO_KEY_PASSWORD >> gradle.properties
          echo "ANDLOILO_KEYSTORE_PASSWORD="$ANDLOILO_KEYSTORE_PASSWORD >> gradle.properties
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
       - run:
         name: Download Dependencies
         command: ./gradlew androidDependencies
        
  save_gradle:
    steps:
      - save_cache:
        paths:
          - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
  build:
    setup:
      executor:
        name: default      
    steps:
    - checkout
    - restore_gradle
    - set_properties
    - save_gradle
    - run:
        name: Run Tests
        command: ./gradlew clean assembleRelease
    - run:
        name: Run Build For AndroidTest
        command: ./gradlew assembleAndroidTest
        
  deploy:
    build:
      setup:
        executor:
          name: default      
      steps:
        - checkout
        - restore_gradle
        - set_properties
        - save_gradle
        - run:
          name: Run Tests
          command: ./gradlew clean assembleRelease
        - run: 
          name: deploy
          command: echo deployed!!
        
workflows:
  version: 2.1
  workflow:
    jobs:
      - build:
        filters:
          branches:
            ignore:
              - master
      - deploy:
        requires:
          - build
        filters:
          branches:
            only:
              - master
